### ISSUE TITLE
Name of file is not used if we define a path

### ISSUE THREAD

**Issue by VoidAndAny** [weareinteractive/ansible-htpasswd#4]
path variable, if defined, must be the full path (directory and filename), the name variable is not used.

Solution, change the task like this : 

```
- name: Adding htpasswd files
  htpasswd:
    name: "{{ item.1.name }}"
    path: "{{ item.0.path | default(htpasswd_path) ~ '/' ~ item.0.name }}"
```

But it break compatibility with previously configured playbook.
